name: Ejecutar Tests

on: push

jobs:
  ejecutar_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar el código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x' 

      - name: Probar codigo
        run: python3 main.py
      - name: Crear imagen Docker
        run: docker build -t LagadGlav/Ej1
      - name: Probar contenedor
        run: docker run LagadGlav/Ej1
